"""task params

Revision ID: 8c5257af99f6
Revises: 315e969176a5
Create Date: 2025-04-26 01:44:32.997457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5257af99f6'
down_revision: Union[str, None] = '315e969176a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('annotators_count', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('days_to_complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'days_to_complete')
    op.drop_column('tasks', 'annotators_count')
    # ### end Alembic commands ###
