"""roles

Revision ID: b4258d2a7e30
Revises: d6ae049db4ce
Create Date: 2025-04-24 23:31:59.281329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4258d2a7e30'
down_revision: Union[str, None] = 'd6ae049db4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_image_rating', 'image_ratings', type_='foreignkey')
    op.alter_column('roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint('uq_user_id_role', 'roles', type_='unique')
    op.drop_column('roles', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('uq_user_id_role', 'roles', ['user_id', 'name'])
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_image_rating', 'image_ratings', 'images', ['image_fid', 'image_code'], ['fid', 'code'])
    # ### end Alembic commands ###
