"""track inappropriate images

Revision ID: cb78fd2c0467
Revises: 9aef398b6563
Create Date: 2025-05-13 18:14:46.803033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb78fd2c0467'
down_revision: Union[str, None] = '9aef398b6563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('inappropriate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'inappropriate')
    # ### end Alembic commands ###