"""Init

Revision ID: d3f5000baea1
Revises: 
Create Date: 2025-04-09 15:29:06.543056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f5000baea1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint(
        'uq_image_fid_code',
        'images',
        ['fid', 'code']
    )

    # 2. Add the new column to image_ratings
    op.add_column('image_ratings', sa.Column('image_code', sa.String()))

    # 3. Backfill data
    op.execute("""
            UPDATE image_ratings ir
            SET image_code = i.code
            FROM images i
            WHERE ir.image_fid = i.fid
        """)

    # 4. Now create the foreign key
    op.create_foreign_key(
        'fk_image_rating',
        'image_ratings', 'images',
        ['image_fid', 'image_code'], ['fid', 'code'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_image_fid_code', 'images', type_='unique')
    op.drop_constraint('fk_image_rating', 'image_ratings', type_='foreignkey')
    op.drop_column('image_ratings', 'image_code')
    # ### end Alembic commands ###
